// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtw1ZxNPvzYTcAyrQJ1AwLRDaRC9S1wlo',
    appId: '1:744308935147:web:b232f3797b584a63d7b1ae',
    messagingSenderId: '744308935147',
    projectId: 'braintree-payment',
    authDomain: 'braintree-payment.firebaseapp.com',
    storageBucket: 'braintree-payment.appspot.com',
    measurementId: 'G-1PQ0NJ30XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzGTK5gzGUHqe-ysRRrcINq1CJ3MEL4c',
    appId: '1:744308935147:android:eb380ed9eef9ba4cd7b1ae',
    messagingSenderId: '744308935147',
    projectId: 'braintree-payment',
    storageBucket: 'braintree-payment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByD4OBkkro8sDDit7ND3dU-33sOAPDS6c',
    appId: '1:744308935147:ios:8935a65b9293f814d7b1ae',
    messagingSenderId: '744308935147',
    projectId: 'braintree-payment',
    storageBucket: 'braintree-payment.appspot.com',
    iosClientId: '744308935147-js1pq8ja5ekmu3078s2a1a8j35mrgdsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPaypalIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByD4OBkkro8sDDit7ND3dU-33sOAPDS6c',
    appId: '1:744308935147:ios:8935a65b9293f814d7b1ae',
    messagingSenderId: '744308935147',
    projectId: 'braintree-payment',
    storageBucket: 'braintree-payment.appspot.com',
    iosClientId: '744308935147-js1pq8ja5ekmu3078s2a1a8j35mrgdsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPaypalIntegration',
  );
}
